theme: jekyll-theme-minimal
google_analytics: G-3YT37GPBBQ
title: ADRVMICRRev.2 SupportSite
logo: https://bit-trade-one.co.jp/wp/wp-content/uploads/2022/06/f4d94dffc9d1d40169a9710aa342769b-1-1.jpg
description: REVIVE-USB-Micro-Rev.2のサポートサイトです。
show_downloads: false
