theme: jekyll-theme-minimal
title: ADRVMICR2 SupportSite
logo: https://bit-trade-one.co.jp/wp/wp-content/uploads/2022/06/f4d94dffc9d1d40169a9710aa342769b-1-コピー.jpg
description: REVIVE-USB-Micro-Rev.2のサポートサイトです。
show_downloads: false
